### ISSUE TITLE
MVP Feature: User can create a memory

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new post labeled as a memory.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click a create post button that leads them to a page where they can choose whether their post is a memory or an event. For this case, memory posts include an input for images, location and caption. Captions are however, optional. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![](https://i.gyazo.com/667f1ce59b058081c7bca01e10602465.png)
## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Set up postgreSql database 
- [x] Update `schema.sql` to include dbdesigner schema under drop schema

### ☁️ Server

- [x] Update `server/index.js` to to handle POST requests to database to push newly created memories
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] In the body, create a form component 
- [x] Set up css layouts for media desktops and mobile
- [x] Include a file input styled to be the size of the image
- [x] Include a text input for location
- [x] Include a textarea input for caption (can be left empty)
- [x] Include a submit button 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
