### ISSUE TITLE
MVP Feature: User can create an event

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new post labeled as an event.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click whether their post is a memory or an event. For this case, an event post includes an input for images, location and caption. Captions are however, optional. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/42393951/139943311-3b43a574-a468-4bbe-b00e-cf4efb7d4a2e.png)
![image](https://user-images.githubusercontent.com/42393951/139943617-094a6cfd-de15-4eb3-b6ab-d406b2d2892c.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include an eventDate column (could be null for memory posts)

### ☁️ Server
- [x] Update `server/index.js` to to handle POST requests to database to push newly created events
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] In the body, create a form component 
- [x] Set up css layouts for media desktops and mobile
- [x] Include a file input styled to be the size of the image
- [x] Add a toggle to switch from Memory and Event
- [x] If Event, add a `<input type="datetime-local">`
- [x] Include a textarea input for caption (can be left empty)
- [x] Include a submit button 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
