### ISSUE TITLE
MVP Feature: User can view all posts

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all posts on the home page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can view all posts on the home page. Users will also have access to a side navigation bar and if the user is on mobile, access to the footer navigation. Now the user can switch from home to create a post.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/42393951/139971165-46288380-0c92-4fd1-9f59-996b0498fd32.png)
![image](https://user-images.githubusercontent.com/42393951/139971179-e8683f36-b46e-4bf1-8631-517b2c2b062c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
 - [x] Update server/index.js to handle GET requests from the database to pull event information (postType, imageUrl, caption, eventDate, location)
 - [x] Test with HTTPie
 - [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a component in `client/pages` to showcase all events
- [x] Each list item post will include an image
- [x] Each list item post will include a title
- [x] Each list item post will include a location
- [x] Each list item post can have an optional caption and eventDate, if it is an event post
- [x] Create a component, side drawer, in `client/components` for navigation
- [x] Add anchors for home and create a post
- [x] Create a component, bottom navigation, in `client/components` for mobile devices
- [x] Include icons and include routes for home and create a post

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
