### ISSUE TITLE
MVP Feature: User can comment on a memory post

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on a memory post and view all comments
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User has the ability to click a button to leave comments on a memory type post. User can then see all comments left on memory posts

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/42393951/140464375-b7f385a4-8721-4cf7-aa54-e1b4c8e01e65.png)
![image](https://user-images.githubusercontent.com/42393951/140464461-873f016c-bd95-467f-ad4a-7cfbe1251150.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x]  Update `server/index.js` to handle GET requests to database to grab all comments specific to postId 
- [x] Update `server/index.js` to handle POST requests to database to push comment
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Convert post component into a class
- [x] Create a commentForm component in `client/pages` to allow users to save their comments on a post
- [x] Include commentForm in post component
- [x] Conditionally render modal to appear based on state of show prop
- [x] Include options to cancel their input and close the modal or submit
- [x] Display retrieved comments in a list on each post component in postList
- [x] Display when the comment was created from the date now.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
