### ISSUE TITLE
MVP Feature: User can RSVP to an event

### ISSUE THREAD

**Issue by PeterVila** [PeterVila/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can RSVP to an event.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on the attending button on `event` type posts to get added to the list. At the bottom of the event post card will be a list of attendees.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/42393951/141429495-5d6c201f-ef78-47a6-ad3d-a41c71999046.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x]  Update `server/index.js` to handle POST requests to database to push an attendee's userId, avatarUrl and postId
- [x] Update `server/index.js` and modify GET requests to database for posts to also include event attendees
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Add a toggle button on each `event` post to listen for clicks
- [x] Add a state for isAttending and set to false
- [x] Create css class for isAttending and one for the opposite, depending on state
- [x] Create a state component for the list of attendees
- [x] On mount, check if the current user logged in matches the attendees, if a match is found, make state turned to true.
- [x] On click, If a match is not found, a click to the attending button sends (avatarUrl, postId and userId) to server.
  - [x] Also concatenates the result to the list of users attending
- [x] Create a component for showcasing all the attendees.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
